// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'El proyecto Planifiko-Prod no está configurado para Web.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'El proyecto Planifiko-Prod no está configurado para iOS.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'El proyecto Planifiko-Prod no está configurado para mac.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'El proyecto Planifiko-Prod no está configurado para windows.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnVFUMB2EgON3wvp_OeVcVkUoqUMHYFVQ',
    appId: '1:329600917340:android:548a8709eb5e002f09eb99',
    messagingSenderId: '329600917340',
    projectId: 'planifiko-prod',
    storageBucket: 'planifiko-prod.firebasestorage.app',
  );


}