// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_-KlVbvBORb2yspB-2fZ8h6RrD8_Ityw',
    appId: '1:783287914373:web:094ae9611af45ad333beec',
    messagingSenderId: '783287914373',
    projectId: 'muchik-tec-noti',
    authDomain: 'muchik-tec-noti.firebaseapp.com',
    storageBucket: 'muchik-tec-noti.firebasestorage.app',
    measurementId: 'G-7VTP6K7HQT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMOHhwX-8RPjQO9mUq32-_cLiS_LhkEmc',
    appId: '1:783287914373:android:d9e146650b1e93cf33beec',
    messagingSenderId: '783287914373',
    projectId: 'muchik-tec-noti',
    storageBucket: 'muchik-tec-noti.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAG3FugdPLpzpJgbfVKtvALkamIS5dZFJE',
    appId: '1:783287914373:ios:5d9fcdaac09d82a633beec',
    messagingSenderId: '783287914373',
    projectId: 'muchik-tec-noti',
    storageBucket: 'muchik-tec-noti.firebasestorage.app',
    iosBundleId: 'com.economuchik.appMuchik',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAG3FugdPLpzpJgbfVKtvALkamIS5dZFJE',
    appId: '1:783287914373:ios:5d9fcdaac09d82a633beec',
    messagingSenderId: '783287914373',
    projectId: 'muchik-tec-noti',
    storageBucket: 'muchik-tec-noti.firebasestorage.app',
    iosBundleId: 'com.economuchik.appMuchik',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_-KlVbvBORb2yspB-2fZ8h6RrD8_Ityw',
    appId: '1:783287914373:web:d5b0f91d7779dd0c33beec',
    messagingSenderId: '783287914373',
    projectId: 'muchik-tec-noti',
    authDomain: 'muchik-tec-noti.firebaseapp.com',
    storageBucket: 'muchik-tec-noti.firebasestorage.app',
    measurementId: 'G-F5RS26M665',
  );

}